<!doctype html>
<html>
<head>
	<meta charset='UTF-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <meta name="mobile-web-app-capable" content="yes">
        <meta name=apple-mobile-web-app-status-bar-style content=black>
        <title>Login</title>
        <link type="text/css" rel="stylesheet" href="assets/template/login/css/login.css" /> 
</head>

<body>
	<div id='body'>
            <div class="wrap"> 
            <?= $content ?>
            </div>
	</div>
    
    
	<script src="assets/js/jquery/jquery-1.11.2.min.js"></script>

</body>

</html>