<!doctype html>
<?php global $session; $userSes = ($session->get_session('userSes')); ?>
<html>
<head>
	<meta charset='UTF-8' />
        <title>Live</title>
        
        <link rel="shortcut icon" HREF="<?=  assets_url('img/favicon.ico')?>" />
        
        <link href="<?=assets_url('fonts/font-awesome/css/font-awesome.css')?>" rel="stylesheet" />
        <link type="text/css" rel="stylesheet" href="<?=assets_url('c/navigation/css/main.css')?>" />
        <link type="text/css" rel="stylesheet" href="<?=assets_url('t/app/css/main.css')?>" />
	<style>
		input, textarea {border:1px solid #CCC;margin:0px;padding:0px}

		#log {width:100%;height:400px}
		#message {width:100%;line-height:20px}
	</style>
        <script>
            var app_url = '<?= site_url()?>';
            var processId = <?=$processId?>;
            var sessionId = <?=$userSes->getID()?>;
        </script>
</head>

<body>
        <div class="wrap">
            <div class="header">
                <img src="<?=assets_url('t/app/img/logo.png')?>" />
                
                <?= \components\process\headername\Component::Display() ?>
                
                <?= \components\user\quick_user\Component::Display() ?>
            </div>
            <?= components\navigation\main\Component::Display() ?>
            <div id='body'>
                <?= $content ?>
            </div>
        </div>
    
    
        <div class="footer-status clr">
            
            <?= \components\server\info\Component::Display() ?>
            
            <?= \components\message\footer\Component::Display() ?>
            
        </div>
    
	<script src="<?=assets_url('js/jquery/jquery-1.11.2.min.js')?>"></script>
        <script src="<?=assets_url('js/cookie/jquery.cookie.js')?>"></script>
        <script src="<?=assets_url('js/core/definition.js')?>"></script>
        <script src="<?=assets_url('js/core/functions.js')?>"></script>
        <script src="<?=assets_url('js/moment/jquery.timeago.js')?>"></script>
	<script src="<?=assets_url('js/server/x.js')?>"></script>
        <script src="<?=assets_url('js/core/listener.js')?>"></script>
        <script src="<?=assets_url('js/message/core.footer_items.js')?>"></script>
        
        <script src="<?=assets_url('js/core/app.js')?>"></script>
</body>

</html>