<!doctype html>
<?php global $session; $userSes = ($session->get_session('userSes')); ?>
<html>
<head>
	<meta charset='UTF-8' />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0"/>
        <meta name="mobile-web-app-capable" content="yes">
        <meta name=apple-mobile-web-app-status-bar-style content=black>
        <title>Live</title>
        
        <link rel="shortcut icon" HREF="<?=  assets_url('img/favicon.ico')?>" /> 
        
        <link href="<?=assets_url('fonts/font-awesome/css/font-awesome.css?v='.VERSION)?>" rel="stylesheet" /> 
        
        <?= \resource_manager\Concate_Files::DisplayCSS() ?>
       <?php if(!ASSETS_CONCAT): ?> 
        <script> var app_url = '<?= site_url()?>'; var processId = <?=$processId?>; var sessionId = <?=$userSes->getID()?>; </script>
        <?php endif; ?> 
        <?= \resource_manager\Concate_Files::DisplayMainJS() ?>
        
</head>

<body id="bodypage">
        <div class="wrap animate">
            <div class="header">
                <img src="<?=assets_url('t/app/img/logo.png')?>" />
                
                <?= \components\process\headername\Component::Display() ?>
                
                <?= \components\user\quick_user\Component::Display() ?>
            </div>
            <?= components\navigation\main\Component::Display() ?>
            <div id='body'>
                <?= $content ?>
            </div>
        </div>
    
    
        <div class="footer-status clr">
            
            <?= \components\server\info\Component::Display() ?>
            
            <?= \components\message\footer\Component::Display() ?>
            
        </div>
    
        
        <div class="alert-box animate-med boxsizing" ></div>
	
        <?= \resource_manager\Concate_Files::DisplayJS() ?>
        
        <?php print_r(core::$Detect->isMobilePhone) ?>
        
</body>

</html>